spring:
 datasource:
  url: jdbc:postgresql://localhost:5433/exchangeRatesServiceDB
  username: root
  password: toor
 liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.xml
 jpa:
  open-in-view: false
  properties:
   hibernate:
    default_schema: public

server:
 port: 8087

global:
 exception-handling:
  debug-message: TRUE
