spring:
 datasource:
  url: jdbc:postgresql://localhost:5434/exchangeRatesSyncServiceDB
  username: root
  password: toor
 liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.xml
 jpa:
  open-in-view: false
  properties:
   hibernate:
    default_schema: public

server:
 port: 8088

exchange-rate-service:
 url: http://localhost:8087/api/exchange-rates

websocket:
 suffix: /ws/messages
