spring:
 datasource:
  url: jdbc:postgresql://localhost:5435/exchangeRatesConsumerServiceDB
  username: root
  password: toor
 liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.xml
 jpa:
  open-in-view: false
  properties:
   hibernate:
    default_schema: public

server:
 port: 8089

websocket:
 url: ws://localhost:8088/ws/messages
